## Ramala Prasanth
## CB.EN.U4CSE20249
## Data Science Assignment 1


Generate a tuple from the set ["aman", "222", 777, 400.4] 

In [ ]:
my_tuple=('aman','222',700,44.4)

In [ ]:
my_dict={"roll NO":"CB.EN.U4CSE20249","Name:":"R Prasanth","DOB": "20 spet 2002"}
print(my_dict)

{'roll NO': 'CB.EN.U4CSE20249', 'Name:': 'R Prasanth', 'DOB': '20 spet 2002'}


In [ ]:
from google.colab import drive

In [ ]:
def simple_interest(p,t,r):
  print("The principal is: ",p)
  print("The time period: ",t)
  print("The rate of interest is: ",r)
  si = (p*t*r)/100
  print("simple interest is : ",si)

simple_interest(1000,2,5)

The principal is:  1000
The time period:  2
The rate of interest is:  5
simple interest is :  100.0


In [2]:
import numpy as np
from numpy import random
np.random.seed(5)
x=random.randint(10,size=(3,2))
print(x)



[[3 6]
 [6 0]
 [9 8]]


In [21]:
y = random.rand()
print(y)
abs(-1234)

0.3541380429150014


1234

In [22]:
z = random.randint(20,90)
print(z)

27


In [36]:
pop = [11,12,13,14,15]
np.random.shuffle(pop)
print(pop)
print(pop[random.randint(0,5)])
temp=[pop.pop(random.randint(0,5)),pop.pop(random.randint(0,4)),pop.pop(random.randint(0,3))]
print(temp)

[14, 13, 11, 15, 12]
15
[15, 12, 14]


In [38]:
f = open('test.txt','w')
f.write('The King is Dead, Long Live The King')
f.close()
f = open('test.txt','r')
for i in f:
  print(i,end=" ")
f.close()

The King is Dead, Long Live The King 

In [44]:
test = 'The King is Dead, Long Live The King'
array = test.split()
print(test)
print(test[2:5])
print(test[2:])


The King is Dead, Long Live The King
e K
e King is Dead, Long Live The King


In [49]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [52]:
print(arr[1])
print(len(arr))

[4 5 6]
2


In [56]:
arr = random.randint(20,size=(10))
print(arr)
x = arr.reshape(2,5)
print(x)

[12  5 11  5  9  5 18  1 15  6]
[[12  5 11  5  9]
 [ 5 18  1 15  6]]


In [4]:
arr = np.array([1,1,4,5,5,7])
np.unique(arr)

array([1, 4, 5, 7])

In [5]:
arr1=np.array([1,2,3])
arr2=np.array([0,1,1])
np.dot(arr1,arr2)


5

In [7]:
matrix = np.array([[2,-12],[1,-5]])
a,b = np.linalg.eig(matrix)
print(a,b)#eigen values, eigen vectors

[-1. -2.] [[0.9701425  0.9486833 ]
 [0.24253563 0.31622777]]
